# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.9 on 2016-05-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20160425_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipevent',
            name='stripe_charge',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
