# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.9 on 2016-10-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_tipevent_stripe_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipuser',
            name='sms_number',
        ),
        migrations.AlterField(
            model_name='tipevent',
            name='tipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip_events', to='payments.TipUser'),
        ),
    ]
