# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_tipuser_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtip',
            old_name='strip_subscription_id',
            new_name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='tipuser',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='recurringtip',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
