# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 01:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20161024_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtip',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tipevent',
            name='occurred_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tipuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
