# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20161026_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipuser',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
