# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20161026_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipuser',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
