# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_tipuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
