# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_auto_20160118_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='total_tips',
            field=models.PositiveIntegerField(default=0, help_text='Tips collected over podcast lifetime in cents'),
        ),
    ]
