# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.9 on 2016-04-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_podcast_total_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='author_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='language',
            field=models.CharField(default=b'en-US', max_length=16),
        ),
    ]
