# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_podcast_total_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='homepage',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='rss_redirect',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
