# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20160414_0301'),
        ('podcasts', '0012_auto_20160419_1743'),
    ]

    operations = [
    ]
