# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='homepage',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
