# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.9 on 2016-05-03 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_auto_20160503_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastreviewassociation',
            name='podcast',
        ),
        migrations.DeleteModel(
            name='PodcastReviewAssociation',
        ),
    ]
