# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0017_auto_20160508_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='description_flair',
        ),
    ]
