# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.9 on 2016-05-08 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0018_remove_podcastepisode_description_flair'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='flair_tip_jar',
            field=models.BooleanField(default=False),
        ),
    ]
