# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0020_auto_20160514_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='author_name',
            field=models.CharField(default=b'Anonymous', max_length=1024),
        ),
    ]
