# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.9 on 2016-10-22 23:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0021_auto_20160806_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='homepage',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
