# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.9 on 2016-10-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0022_auto_20161022_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
