# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0026_auto_20161127_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='stats_base_listens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
