# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0027_podcastepisode_stats_base_listens'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='flair_referral_code',
            field=models.BooleanField(default=False),
        ),
    ]
