# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0028_podcastepisode_flair_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='private_access_min_subscription',
            field=models.PositiveIntegerField(default=None, help_text='Min sub value in cents', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='private_after_age',
            field=models.PositiveIntegerField(default=None, help_text='Age in seconds', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='private_after_nth',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Overrides other settings when true'),
        ),
    ]
