# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0029_auto_20170221_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='publish',
            field=models.DateTimeField(db_index=True),
        ),
    ]
