# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160118_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='stripe_payout_recipient',
            new_name='stripe_payout_managed_account',
        ),
    ]
