# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160403_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BetaRequest',
        ),
    ]
