# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_betarequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
