# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20161026_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='coupon_code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
