# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usersettings_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='coupon_code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
