# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20161127_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
