# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('accounts', '0015_auto_20161227_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='api_token',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersettings', to='authtoken.Token'),
        ),
    ]
