# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_remove_site_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='theme',
            field=models.CharField(choices=[(b'panther', 'Panther'), (b'podcasty', 'Podcasty'), (b'zen', 'Zen')], max_length=16),
        ),
    ]
