# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20160327_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='itunes_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='stitcher_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitelink',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
