# -*- coding: utf-8 -*-
from __future__ import absolute_import
# Generated by Django 1.10.2 on 2016-11-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20161026_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='disqus_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='show_itunes_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteblogpost',
            name='disable_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='theme',
            field=models.CharField(choices=[(b'panther', 'Panther'), (b'podcasty', 'Podcasty'), (b'zen', 'Zen'), (b'unstyled', 'Unstyled')], max_length=16),
        ),
    ]
