# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 19:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_auto_20161117_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='analytics_id',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-]*$', 'Only GA IDs are accepted')]),
        ),
        migrations.AlterField(
            model_name='site',
            name='theme',
            field=models.CharField(choices=[('panther', 'Panther'), ('podcasty', 'Podcasty'), ('zen', 'Zen'), ('unstyled', 'Unstyled')], max_length=16),
        ),
    ]
