# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_auto_20161127_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('page_type', models.CharField(choices=[('markdown', 'Markdown'), ('hosts', 'Hosts'), ('contact', 'Contact')], max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
