# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_sitepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitelink',
            name='class_name',
        ),
    ]
