# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_remove_sitelink_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='google_play_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
