# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcasts', '0023_auto_20161026_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[(b'webhook', 'Webhook'), (b'slack', 'Slack'), (b'email', 'Email')], max_length=32)),
                ('destination', models.CharField(max_length=512)),
                ('trigger', models.CharField(choices=[(b'tip', 'On Tip'), (b'feedback', 'On Feedback'), (b'first_listen', 'On Episode First Listen'), (b'listen_threshold', 'On Hit Listen Threshold'), (b'growth_milestone', 'On Hit Growth Milestone')], max_length=32)),
                ('condition', models.CharField(blank=True, max_length=64, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='podcasts.Podcast')),
            ],
        ),
    ]
