# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhook',
            name='destination_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('slack', 'Slack'), ('email', 'Email')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationhook',
            name='trigger',
            field=models.CharField(choices=[('tip', 'On Tip'), ('feedback', 'On Feedback'), ('first_listen', 'On Episode First Listen'), ('listen_threshold', 'On Episode Hit Listen Threshold'), ('growth_milestone', 'On Hit Growth Milestone')], max_length=32),
        ),
    ]
